[Qt]
style=Fusion
font="Avenir Next,10,-1,5,50,0,0,0,0,0"
Palette\active=#1c1b24, #efedf8, #ffffff, #f7f5fc, #d9d4ea, #e3dff2, #1c1b24, #ffffff, #1c1b24, #ffffff, #efedf8, #1c1b24, #8371f7, #ffffff, #2e7cf6, #ed6ce0
Palette\inactive=#1c1b24, #efedf8, #ffffff, #f7f5fc, #d9d4ea, #e3dff2, #1c1b24, #ffffff, #1c1b24, #ffffff, #efedf8, #1c1b24, #9c8ef9, #ffffff, #2e7cf6, #ed6ce0
Palette\disabled=#9a96ac, #efedf8, #ffffff, #f7f5fc, #d9d4ea, #e3dff2, #9a96ac, #ffffff, #9a96ac, #ffffff, #efedf8, #9a96ac, #d9d4ea, #ffffff, #2e7cf6, #ed6ce0
