#!/usr/bin/env python3
"""popular-apps.py - the curated seed database (Phase 9.5).

This is the Store's *search seed*, not its catalog: the crawler starts from
these projects instead of waiting for AppImageHub to surface them, and every
entry is still resolved, downloaded and ELF-verified before it can be published.

Each row:  (display name, xxri category, "owner/repo" | "" , tier)

  tier 1  flagship desktop software everyone recognises
  tier 2  very widely used
  tier 3  well known within its niche
  tier 4  known, smaller audience

Tier feeds the ranking (with GitHub stars, release recency and whether an i686
build actually exists), so mainstream software leads the home page and obscure
software stays searchable but never dominates.
"""

SEEDS = [
# ------------------------------------------------------------------ browsers
("Firefox",              "browser", "srevinsaju/Firefox-Appimage", 1),
("Chromium",             "browser", "macchrome/linchrome",         1),
("Brave",                "browser", "brave/brave-browser",         1),
("Ungoogled Chromium",   "browser", "ungoogled-software/ungoogled-chromium", 2),
("LibreWolf",            "browser", "librewolf-community/browser-linux", 2),
("Falkon",               "browser", "KDE/falkon",                  3),
("Min",                  "browser", "minbrowser/min",              3),
("Otter Browser",        "browser", "OtterBrowser/otter-browser",  3),
("qutebrowser",          "browser", "qutebrowser/qutebrowser",     3),
("Waterfox",             "browser", "BrowserWorks/Waterfox",       3),
("Thorium",              "browser", "Alex313031/thorium",          3),
("Floorp",               "browser", "Floorp-Projects/Floorp",      3),
("Zen Browser",          "browser", "zen-browser/desktop",         3),
("Nyxt",                 "browser", "atlas-engineer/nyxt",         4),
("Beaker Browser",       "browser", "beakerbrowser/beaker",        4),
("Wexond",               "browser", "wexond/browser-base",         4),

# -------------------------------------------------------------------- office
("LibreOffice",          "office",  "",                            1),
("ONLYOFFICE Desktop",   "office",  "ONLYOFFICE/DesktopEditors",   1),
("Joplin",               "office",  "laurent22/joplin",            1),
("Obsidian",             "office",  "obsidianmd/obsidian-releases",1),
("Logseq",               "office",  "logseq/logseq",               2),
("Standard Notes",       "office",  "standardnotes/app",           2),
("Zettlr",               "office",  "Zettlr/Zettlr",               2),
("QOwnNotes",            "office",  "pbek/QOwnNotes",              3),
("Marktext",             "office",  "marktext/marktext",           2),
("Typora-like Notable",  "office",  "notable/notable",             3),
("Trilium Notes",        "office",  "zadam/trilium",               3),
("AppFlowy",             "office",  "AppFlowy-IO/AppFlowy",        2),
("Focalboard",           "office",  "mattermost/focalboard",       3),
("SiYuan",               "office",  "siyuan-note/siyuan",          3),
("Scribus",              "office",  "scribusproject/scribus",      3),
("Master PDF Editor",    "office",  "",                            3),
("PDF Arranger",         "office",  "pdfarranger/pdfarranger",     3),
("Okular",               "office",  "KDE/okular",                  2),
("Xournal++",            "office",  "xournalpp/xournalpp",         3),
("Calibre",              "office",  "kovidgoyal/calibre",          1),
("Foliate",              "office",  "johnfactotum/foliate",        3),
("Zotero",               "office",  "zotero/zotero",               3),
("Anytype",              "office",  "anyproto/anytype-ts",         3),
("Notesnook",            "office",  "streetwriters/notesnook",     3),
("Simplenote",           "office",  "Automattic/simplenote-electron", 3),
("Boostnote",            "office",  "BoostIO/BoostNote-App",       4),
("Turtl",                "office",  "turtl/desktop",               4),

# --------------------------------------------------------------- development
("Visual Studio Code",   "development", "microsoft/vscode",        1),
("VSCodium",             "development", "VSCodium/vscodium",       1),
("Code - OSS",           "development", "microsoft/vscode",        1),
("Neovim",               "development", "neovim/neovim",           1),
("GVim",                 "development", "vim/vim-appimage",        2),
("Sublime-like Lapce",   "development", "lapce/lapce",             2),
("Helix",                "development", "helix-editor/helix",      2),
("Zed",                  "development", "zed-industries/zed",      2),
("Atom-like Pulsar",     "development", "pulsar-edit/pulsar",      3),
("CudaText",             "development", "Alexey-T/CudaText",       3),
("Geany",                "development", "geany/geany",             3),
("Kate",                 "development", "KDE/kate",                3),
("Meld",                 "development", "GNOME/meld",              3),
("DBeaver",              "development", "dbeaver/dbeaver",         2),
("Beekeeper Studio",     "development", "beekeeper-studio/beekeeper-studio", 3),
("Insomnia",             "development", "Kong/insomnia",           2),
("Postman-like Hoppscotch","development","hoppscotch/hoppscotch",  2),
("Bruno",                "development", "usebruno/bruno",          3),
("GitKraken-like GitAhead","development","gitahead/gitahead",      4),
("Gitnuro",              "development", "JetpackDuba/Gitnuro",     4),
("Sourcegit",            "development", "sourcegit-scm/sourcegit", 3),
("Arduino IDE",          "development", "arduino/arduino-ide",     2),
("PlatformIO-like",      "development", "",                        4),
("Android Studio-like",  "development", "",                        4),
("Eclipse Theia",        "development", "eclipse-theia/theia-blueprint", 3),
("Jupyter-like nteract", "development", "nteract/nteract",         3),
("RStudio-like",         "development", "",                        4),
("Fritzing",             "development", "fritzing/fritzing-app",   3),
("appimagetool",         "development", "AppImage/AppImageKit",    3),
("pkg2appimage",         "development", "AppImageCommunity/pkg2appimage", 4),
("Boop GTK",             "development", "zoeyfyi/Boop-GTK",        4),
("Regex101-like Kregexeditor","development","",                    4),
("DevToys",              "development", "DevToys-app/DevToysMac",  3),
("Cutter",               "development", "rizinorg/cutter",         3),
("Ghidra-like",          "development", "",                        4),

# ------------------------------------------------------------------ graphics
("GIMP",                 "graphics", "",                           1),
("Inkscape",             "graphics", "",                           1),
("Krita",                "graphics", "KDE/krita",                  1),
("Blender",              "graphics", "",                           1),
("draw.io",              "graphics", "jgraph/drawio-desktop",      1),
("Pencil2D",             "graphics", "pencil2d/pencil",            3),
("Synfig Studio",        "graphics", "synfig/synfig",              3),
("OpenToonz",            "graphics", "opentoonz/opentoonz",        3),
("MyPaint",              "graphics", "mypaint/mypaint",            3),
("Drawing",              "graphics", "maoschanz/drawing",          4),
("LibreSprite",          "graphics", "LibreSprite/LibreSprite",    3),
("Aseprite-like Pixelorama","graphics","Orama-Interactive/Pixelorama", 3),
("FreeCAD",              "graphics", "FreeCAD/FreeCAD",            2),
("OpenSCAD",             "graphics", "openscad/openscad",          3),
("LibrePCB",             "graphics", "LibrePCB/LibrePCB",          3),
("KiCad",                "graphics", "KiCad/kicad-source-mirror",  2),
("Ultimaker Cura",       "graphics", "Ultimaker/Cura",             2),
("PrusaSlicer",          "graphics", "prusa3d/PrusaSlicer",        2),
("OrcaSlicer",           "graphics", "SoftFever/OrcaSlicer",       2),
("Slic3r",               "graphics", "slic3r/Slic3r",              4),
("Natron",               "graphics", "NatronGitHub/Natron",        3),
("Nomacs",               "graphics", "nomacs/nomacs",              3),
("qView",                "graphics", "jurplel/qView",              3),
("Upscayl",              "graphics", "upscayl/upscayl",            2),

# --------------------------------------------------------------- photography
("darktable",            "photography", "darktable-org/darktable", 2),
("RawTherapee",          "photography", "Beep6581/RawTherapee",    2),
("digiKam",              "photography", "KDE/digikam",             2),
("Shotwell",             "photography", "GNOME/shotwell",          3),
("Photoflare",           "photography", "PhotoFlare/photoflare",   3),
("ART",                  "photography", "artpixls/ART",            4),
("Hugin",                "photography", "",                        4),

# --------------------------------------------------------------------- video
("VLC",                  "video",   "videolan/vlc",                1),
("mpv",                  "video",   "mpv-player/mpv",              1),
("OBS Studio",           "video",   "obsproject/obs-studio",       1),
("Kdenlive",             "video",   "KDE/kdenlive",                1),
("Shotcut",              "video",   "mltframework/shotcut",        1),
("HandBrake",            "video",   "HandBrake/HandBrake",         1),
("Olive Video Editor",   "video",   "olive-editor/olive",          3),
("Flowblade",            "video",   "jliljebl/flowblade",          3),
("Avidemux",             "video",   "mean00/avidemux2",            3),
("SMPlayer",             "video",   "smplayer-dev/smplayer",       3),
("Celluloid",            "video",   "celluloid-player/celluloid",  3),
("Haruna",               "video",   "KDE/haruna",                  3),
("FreeTube",             "video",   "FreeTubeApp/FreeTube",        2),
("Tartube",              "video",   "axcore/tartube",              4),
("MediaElch",            "video",   "Komet/MediaElch",             4),
("Jellyfin Media Player","video",   "jellyfin/jellyfin-media-player", 2),
("Stremio",              "video",   "Stremio/stremio-shell",       2),
("LosslessCut",          "video",   "mifi/lossless-cut",           2),
("Kodi",                 "video",   "xbmc/xbmc",                   1),
("MakeMKV-like",         "video",   "",                            4),
("Vidcutter",            "video",   "ozmartian/vidcutter",         4),

# --------------------------------------------------------------------- audio
("Audacity",             "audio",   "audacity/audacity",           1),
("Tenacity",             "audio",   "tenacityteam/tenacity",       3),
("Ardour",               "audio",   "Ardour/ardour",               2),
("LMMS",                 "audio",   "LMMS/lmms",                   2),
("MuseScore",            "audio",   "musescore/MuseScore",         1),
("Strawberry",           "audio",   "strawberrymusicplayer/strawberry", 2),
("Clementine",           "audio",   "clementine-player/Clementine",2),
("Lollypop",             "audio",   "",                            3),
("Nuclear",              "audio",   "nukeop/nuclear",              3),
("Spotify-like Spotube", "audio",   "KRTirtho/spotube",            2),
("Mixxx",                "audio",   "mixxxdj/mixxx",               2),
("Hydrogen",             "audio",   "hydrogen-music/hydrogen",     3),
("Zrythm",               "audio",   "zrythm/zrythm",               3),
("Helio Workstation",    "audio",   "helio-fm/helio-workstation",  3),
("fre:ac",               "audio",   "enzo1982/freac",              3),
("EasyEffects",          "audio",   "wwmm/easyeffects",            3),
("Sayonara Player",      "audio",   "",                            4),
("Museeks",              "audio",   "martpie/museeks",             4),

# ------------------------------------------------------------- communication
("Telegram Desktop",     "communication", "telegramdesktop/tdesktop", 1),
("Discord",              "communication", "",                      1),
("Signal Desktop",       "communication", "signalapp/Signal-Desktop", 1),
("Element",              "communication", "element-hq/element-desktop", 1),
("Thunderbird",          "communication", "srevinsaju/thunderbird-appimage", 1),
("Slack-like Ferdium",   "communication", "ferdium/ferdium-app",   2),
("Rambox",               "communication", "ramboxapp/download",    2),
("Franz",                "communication", "meetfranz/franz",       3),
("Session",              "communication", "session-foundation/session-desktop", 3),
("Jami",                 "communication", "savoirfairelinux/jami-client-qt", 3),
("Wire",                 "communication", "wireapp/wire-desktop",  3),
("Mattermost",           "communication", "mattermost/desktop",    2),
("Zulip",                "communication", "zulip/zulip-desktop",   3),
("Revolt",               "communication", "revoltchat/desktop",    3),
("Threema",              "communication", "",                      4),
("HexChat",              "communication", "hexchat/hexchat",       3),
("Konversation",         "communication", "KDE/konversation",      4),
("Gajim",                "communication", "",                      4),
("Whatsapp-like Whatsie","communication", "keeeeenw/whatsie",      4),
("Teams for Linux",      "communication", "IsmaelMartinez/teams-for-linux", 2),
("Caprine",              "communication", "sindresorhus/caprine",  3),

# ------------------------------------------------------------------ networking
("qBittorrent",          "networking", "qbittorrent/qBittorrent",  1),
("Transmission",         "networking", "transmission/transmission",1),
("Deluge",               "networking", "deluge-torrent/deluge",    2),
("FileZilla",            "networking", "",                         1),
("WinSCP-like",          "networking", "",                         4),
("Nextcloud Desktop",    "networking", "nextcloud/desktop",        1),
("Syncthing Tray",       "networking", "Martchus/syncthingtray",   2),
("Remmina",              "networking", "FreeRDP/Remmina",          2),
("RustDesk",             "networking", "rustdesk/rustdesk",        1),
("AnyDesk-like",         "networking", "",                         4),
("Motrix",               "networking", "agalwood/Motrix",          2),
("JDownloader-like",     "networking", "",                         4),
("Wireshark-like",       "networking", "",                         3),
("Angry IP Scanner",     "networking", "angryip/ipscan",           3),
("Termius-like",         "networking", "",                         4),
("Warp Terminal",        "networking", "",                         4),
("ProtonVPN",            "networking", "",                         2),
("Mullvad VPN",          "networking", "mullvad/mullvadvpn-app",   2),
("Tailscale-like Trayscale","networking","DeedleFake/trayscale",   4),

# -------------------------------------------------------------------- security
("KeePassXC",            "security", "keepassxreboot/keepassxc",   1),
("Bitwarden",            "security", "bitwarden/clients",          1),
("Cryptomator",          "security", "cryptomator/cryptomator",    2),
("VeraCrypt",            "security", "veracrypt/VeraCrypt",        2),
("Proton Pass",          "security", "",                           3),
("Buttercup",            "security", "buttercup/buttercup-desktop",3),
("Padloc",               "security", "padloc/padloc",              4),
("Authenticator",        "security", "",                           4),
("Crypter",              "security", "HR/Crypter",                 4),
("Picocrypt",            "security", "Picocrypt/Picocrypt",        3),

# ---------------------------------------------------------------------- games
("0 A.D.",               "games",   "0ad/0ad",                     2),
("SuperTux",             "games",   "SuperTux/supertux",           2),
("SuperTuxKart",         "games",   "supertuxkart/stk-code",       2),
("Minetest",             "games",   "minetest/minetest",           2),
("Mindustry",            "games",   "Anuken/Mindustry",            2),
("OpenRA",               "games",   "OpenRA/OpenRA",               2),
("Wesnoth",              "games",   "wesnoth/wesnoth",             2),
("Hedgewars",            "games",   "hedgewars/hedgewars",         3),
("Widelands",            "games",   "widelands/widelands",         3),
("Shattered Pixel Dungeon","games", "00-Evan/shattered-pixel-dungeon", 3),
("Endless Sky",          "games",   "endless-sky/endless-sky",     3),
("OpenTTD",              "games",   "OpenTTD/OpenTTD",             2),
("Cataclysm DDA",        "games",   "CleverRaven/Cataclysm-DDA",   3),
("Veloren",              "games",   "",                            3),
("Xonotic",              "games",   "",                            3),
("Sabaki",               "games",   "SabakiHQ/Sabaki",             4),
("GDLauncher",           "games",   "gorilla-devs/GDLauncher",     3),
("Prism Launcher",       "games",   "PrismLauncher/PrismLauncher", 2),
("Lutris",               "games",   "lutris/lutris",               2),
("Heroic Games Launcher","games",   "Heroic-Games-Launcher/HeroicGamesLauncher", 2),
("ATLauncher",           "games",   "ATLauncher/ATLauncher",       3),

# ------------------------------------------------------------- virtualization
("VirtualBox-like",      "virtualization", "",                     2),
("Gnome Boxes-like",     "virtualization", "",                     3),
("RetroArch",            "virtualization", "libretro/RetroArch",   1),
("Dolphin Emulator",     "virtualization", "dolphin-emu/dolphin",  2),
("PCSX2",                "virtualization", "PCSX2/pcsx2",          2),
("PPSSPP",               "virtualization", "hrydgard/ppsspp",      2),
("DuckStation",          "virtualization", "stenzek/duckstation",  2),
("mGBA",                 "virtualization", "mgba-emu/mgba",        2),
("melonDS",              "virtualization", "melonDS-emu/melonDS",  3),
("DeSmuME",              "virtualization", "TASEmulators/desmume", 3),
("Snes9x",               "virtualization", "snes9xgit/snes9x",     3),
("FCEUX",                "virtualization", "TASEmulators/fceux",   3),
("ScummVM",              "virtualization", "scummvm/scummvm",      2),
("DOSBox Staging",       "virtualization", "dosbox-staging/dosbox-staging", 2),
("BasiliskII",           "virtualization", "cebix/macemu",         4),
("Flycast",              "virtualization", "flyinghead/flycast",   3),
("Citra-like Azahar",    "virtualization", "azahar-emu/azahar",    3),
("Ryujinx-like",         "virtualization", "",                     3),
("openMSX",              "virtualization", "openMSX/openMSX",      4),
("Mesen",                "virtualization", "SourMesen/Mesen2",     3),

# -------------------------------------------------------------------- science
("Stellarium",           "science", "Stellarium/stellarium",       2),
("Celestia",             "science", "CelestiaProject/Celestia",    3),
("GNU Octave-like",      "science", "",                            3),
("Scilab",               "science", "",                            3),
("SageMath-like",        "science", "",                            4),
("QGIS",                 "science", "qgis/QGIS",                   2),
("Marble",               "science", "KDE/marble",                  3),
("LabPlot",              "science", "KDE/labplot",                 3),
("SciDAVis",             "science", "SciDAVis/scidavis",           4),
("Veusz",                "science", "veusz/veusz",                 4),
("Avogadro",             "science", "OpenChemistry/avogadroapp",   3),
("Jmol-like",            "science", "",                            4),
("Subsurface",           "science", "subsurface/subsurface",       3),
("Gnuplot-like",         "science", "",                            4),
("SER Player",           "science", "cgarry/ser-player",           4),

# ------------------------------------------------------------------ education
("Anki",                 "education", "ankitects/anki",            1),
("GeoGebra",             "education", "geogebra/geogebra",         2),
("Kiwix",                "education", "kiwix/kiwix-desktop",       2),
("Klavaro",              "education", "",                          4),
("GCompris",             "education", "",                          3),
("Veyon",                "education", "veyon/veyon",               3),
("OpenBoard",            "education", "OpenBoard-org/OpenBoard",   3),
("Tux Typing",           "education", "",                          4),
("Mnemosyne",            "education", "",                          4),
("Scratch-like TurboWarp","education","TurboWarp/desktop",         3),

# -------------------------------------------------------------------- finance
("GnuCash",              "finance", "Gnucash/gnucash",             2),
("HomeBank",             "finance", "",                            3),
("KMyMoney",             "finance", "KDE/kmymoney",                3),
("Firefly III-like",     "finance", "",                            4),
("Electrum",             "finance", "spesmilo/electrum",           2),
("Exodus-like",          "finance", "",                            3),
("MyCrypto",             "finance", "MyCryptoHQ/MyCrypto",         3),
("Bitcoin Core",         "finance", "bitcoin/bitcoin",             2),
("Monero GUI",           "finance", "monero-project/monero-gui",   2),
("Feather Wallet",       "finance", "feather-wallet/feather",      3),

# --------------------------------------------------------------------- system
("GParted-like",         "system",  "",                            2),
("balenaEtcher",         "system",  "balena-io/etcher",            1),
("Ventoy",               "system",  "ventoy/Ventoy",               1),
("BleachBit",            "system",  "bleachbit/bleachbit",         2),
("Stacer",               "system",  "oguzhaninan/Stacer",          2),
("CPU-X",                "system",  "TheTumultuousUnicornOfDarkness/CPU-X", 3),
("Hardinfo",             "system",  "",                            3),
("Czkawka",              "system",  "qarmin/czkawka",              2),
("Timeshift-like",       "system",  "",                            3),
("AppImageLauncher",     "system",  "TheAssassin/AppImageLauncher",2),
("AppImageUpdate",       "system",  "AppImageCommunity/AppImageUpdate", 3),
("Gear Lever",           "system",  "mijorus/gearlever",           3),
("Mission Center",       "system",  "",                            3),
("Resources",            "system",  "nokyan/resources",            3),

# ------------------------------------------------------------------ utilities
("KeePass-like",         "utilities", "",                          3),
("Flameshot",            "utilities", "flameshot-org/flameshot",   1),
("ksnip",                "utilities", "ksnip/ksnip",               3),
("Peek",                 "utilities", "phw/peek",                  3),
("PeaZip",               "utilities", "peazip/PeaZip",             2),
("Ark-like",             "utilities", "",                          3),
("Double Commander",     "utilities", "doublecmd/doublecmd",       3),
("Krusader",             "utilities", "KDE/krusader",              3),
("Files-like Nautilus",  "utilities", "",                          3),
("Meld-like Diffuse",    "utilities", "",                          4),
("KDiff3",               "utilities", "KDE/kdiff3",                3),
("Bulk Rename-like",     "utilities", "",                          4),
("Cool Retro Term",      "utilities", "Swordfish90/cool-retro-term",3),
("Tabby Terminal",       "utilities", "Eugeny/tabby",              2),
("Alacritty",            "utilities", "alacritty/alacritty",       1),
("WezTerm",              "utilities", "wez/wezterm",               2),
("Kitty",                "utilities", "kovidgoyal/kitty",          1),
("Hyper",                "utilities", "vercel/hyper",              2),
("eDEX-UI",              "utilities", "GitSquared/edex-ui",        3),
("Etcher-like Rufus",    "utilities", "",                          3),
("windows2usb",          "utilities", "ValdikSS/windows2usb",      4),
("Nyrna",                "utilities", "Merrit/nyrna",              4),
("Ferdi",                "utilities", "getferdi/ferdi",            4),
("Pennywise",            "utilities", "kamranahmedse/pennywise",   4),
("Tusk",                 "utilities", "klaudiosinani/tusk",        4),

# ----------------------------------------------------------------- productivity
("Todoist-like Super Productivity","productivity","johannesjo/super-productivity", 2),
("Planner",              "productivity", "alainm23/planify",       3),
("Tasks",                "productivity", "",                       4),
("ActivityWatch",        "productivity", "ActivityWatch/activitywatch", 2),
("Toggl-like",           "productivity", "",                       4),
("Pomatez",              "productivity", "zidoro/pomatez",         3),
("Flameshot-like Notes", "productivity", "",                       4),
("Cherrytree",           "productivity", "giuspen/cherrytree",     3),
("Freeplane",            "productivity", "freeplane/freeplane",    3),
("Heimer",               "productivity", "juzzlin/Heimer",         4),
("Mindmap-like",         "productivity", "",                       4),

# ------------------------------------------------------------------------- ai
("Jan",                  "ai",      "menloresearch/jan",           2),
("GPT4All",              "ai",      "nomic-ai/gpt4all",            2),
("LM Studio-like Msty",  "ai",      "",                            3),
("Ollama-like Alpaca",   "ai",      "Jeffser/Alpaca",              3),
("Upscayl AI",           "ai",      "upscayl/upscayl",             2),
("Whisper-like Buzz",    "ai",      "chidiwilliams/buzz",          3),

# ----------------------------------------------------------------- accessories
("Calculator-like Qalculate","accessories","Qalculate/qalculate-gtk", 3),
("Gnome Calculator-like","accessories", "",                        4),
("Color Picker",         "accessories", "",                        4),
("Emoji Picker",         "accessories", "",                        4),
("Clipboard Manager",    "accessories", "",                        4),
("Stretchly",            "accessories", "hovancik/stretchly",      3),
("Caffeine-like",        "accessories", "",                        4),
("Chrome-like Cromite",  "browser", "uazo/cromite",                3),
("Midori",               "browser", "goastian/midori-desktop",     4),
("Konqueror",            "browser", "KDE/konqueror",               4),
("Tor Browser-like",     "browser", "",                            3),
("Vivaldi",              "browser", "",                            2),
("Opera",                "browser", "",                            2),
("Epiphany",             "browser", "GNOME/epiphany",              3),
("SoftMaker FreeOffice", "office",  "",                            2),
("WPS Office",           "office",  "",                            2),
("AbiWord",              "office",  "",                            3),
("Gnumeric",             "office",  "",                            3),
("Sigil",                "office",  "Sigil-Ebook/Sigil",           3),
("MuPDF-like Zathura",   "office",  "",                            3),
("PDFsam",               "office",  "torakiki/pdfsam",             3),
("Stirling PDF-like",    "office",  "",                            3),
("LanguageTool-like",    "office",  "",                            4),
("Nextcloud Notes-like", "office",  "",                            4),
("Emacs",                "development", "",                        1),
("IntelliJ-like",        "development", "",                        2),
("PyCharm-like",         "development", "",                        2),
("Eclipse",              "development", "",                        2),
("NetBeans",             "development", "",                        3),
("Qt Creator",           "development", "",                        2),
("KDevelop",             "development", "KDE/kdevelop",            3),
("Codeblocks",           "development", "",                        3),
("Bluefish",             "development", "",                        4),
("SQLiteBrowser",        "development", "sqlitebrowser/sqlitebrowser", 2),
("HeidiSQL-like",        "development", "",                        4),
("Redis Insight-like",   "development", "",                        4),
("MongoDB Compass",      "development", "",                        3),
("Wireshark",            "development", "wireshark/wireshark",     2),
("Burp-like ZAP",        "development", "zaproxy/zaproxy",         3),
("Docker Desktop-like",  "development", "",                        3),
("Podman Desktop",       "development", "podman-desktop/podman-desktop", 2),
("Lens Kubernetes",      "development", "lensapp/lens",            2),
("Postman",              "development", "",                        1),
("Figma-like Penpot",    "graphics", "penpot/penpot",              2),
("Photopea-like",        "graphics", "",                           3),
("Vectr-like",           "graphics", "",                           4),
("Karbon",               "graphics", "",                           4),
("Dia Diagram",          "graphics", "",                           3),
("yEd-like",             "graphics", "",                          4),
("Antimony",             "graphics", "mkeeter/antimony",           4),
("Wings3D",              "graphics", "dgud/wings",                 4),
("MeshLab",              "graphics", "cnr-isti-vclab/meshlab",     3),
("Godot Engine",         "graphics", "godotengine/godot",          1),
("Unity-like",           "graphics", "",                          3),
("Ardour-like Reaper",   "audio",   "",                            2),
("Bitwig-like",          "audio",   "",                            3),
("Carla",                "audio",   "falkTX/Carla",                3),
("Guitarix",             "audio",   "",                            4),
("Rosegarden",           "audio",   "",                            4),
("Tuxguitar",            "audio",   "helge17/tuxguitar",           3),
("Audacium",             "audio",   "",                            4),
("Amberol",              "audio",   "",                            3),
("Rhythmbox-like",       "audio",   "",                            3),
("Kid3 Tagger",          "audio",   "",                            3),
("Picard",               "audio",   "metabrainz/picard",           2),
("Feishin",              "audio",   "jeffvli/feishin",             3),
("Cider",                "audio",   "",                            3),
("YouTube Music",        "audio",   "th-ch/youtube-music",         2),
("Jitsi Meet",           "communication", "jitsi/jitsi-meet-electron", 2),
("Zoom-like",            "communication", "",                      2),
("Skype-like",           "communication", "",                      2),
("Viber",                "communication", "",                      3),
("Beeper-like",          "communication", "",                      3),
("Fluent Reader",        "communication", "yang991178/fluent-reader", 3),
("NewsFlash",            "communication", "",                      3),
("Thunderbird-like Betterbird","communication","",                 3),
("Mailspring",           "communication", "Foundry376/Mailspring", 2),
("Geary-like",           "communication", "",                      3),
("Bitwarden-like KeeWeb","security", "keeweb/keeweb",              3),
("Tresorit-like",        "security", "",                           4),
("GnuPG-like Kleopatra", "security", "",                           3),
("ClamAV-like",          "security", "",                           3),
("Firejail-like",        "security", "",                          4),
("OnionShare",           "security", "onionshare/onionshare",      3),
("Tor-like",             "security", "",                           3),
("qBittorrent-like Fragments","networking","",                     3),
("Warpinator",           "networking", "linuxmint/warpinator",     3),
("LocalSend",            "networking", "localsend/localsend",      2),
("KDE Connect",          "networking", "KDE/kdeconnect-kde",       2),
("Snapdrop-like",        "networking", "",                        4),
("Gnome Network-like",   "networking", "",                        4),
("Cockpit-like",         "networking", "",                        4),
("Termius",              "networking", "",                        3),
("PuTTY-like",           "networking", "",                        3),
("MQTT Explorer",        "networking", "thomasnordquist/MQTT-Explorer", 3),
("Insomnium",            "networking", "ArchGPT/insomnium",        4),
("OpenRGB",              "system",  "",                            2),
("Piper",                "system",  "libratbag/piper",             3),
("Solaar",               "system",  "pwr-Solaar/Solaar",           3),
("GreenWithEnvy",        "system",  "",                            3),
("CoreCtrl",             "system",  "",                            3),
("Nvidia-like",          "system",  "",                            4),
("Disk Usage Analyzer",  "system",  "",                            3),
("Bottles",              "system",  "bottlesdevs/Bottles",         2),
("Wine-like",            "system",  "",                            2),
("PlayOnLinux-like",     "system",  "",                            3),
("Waydroid-like",        "system",  "",                            3),
("Flatseal",             "system",  "",                            3),
("Warehouse",            "system",  "",                            3),
("Extension Manager",    "system",  "",                            3),
("Fastfetch-like",       "system",  "",                            4),
("Zettlr-like Apostrophe","productivity","",                       3),
("Ghostwriter",          "productivity", "KDE/ghostwriter",        3),
("Joplin-like Standard", "productivity", "",                       4),
("RedNotebook",          "productivity", "",                       4),
("Zim Wiki",             "productivity", "",                       3),
("Tomboy-like",          "productivity", "",                       4),
("Calcurse-like",        "productivity", "",                       4),
("Thunderbird Calendar", "productivity", "",                       4),
("Minder",               "productivity", "phase1geo/Minder",       4),
("Vym",                  "productivity", "",                       4),
("Gnome Clocks-like",    "accessories", "",                        4),
("Weather-like",         "accessories", "",                        4),
("Font Manager",         "accessories", "FontManager/font-manager",3),
("Gpick",                "accessories", "",                        4),
("Screenkey",            "accessories", "",                        4),
("Kazam-like",           "accessories", "",                        4),
("SimpleScreenRecorder", "accessories", "MaartenBaert/ssr",        3),
("Kooha",                "accessories", "SeaDve/Kooha",            3),
("Blanket",              "accessories", "rafaelmardojai/blanket",  4),
("Gaphor",               "science", "gaphor/gaphor",               4),
("Ipe",                  "science", "otfried/ipe",                 4),
("Maxima-like",          "science", "",                            4),
("Geogebra-like Kalgebra","science","",                            4),
("Step Physics",         "science", "",                            4),
("Kalzium",              "science", "",                            4),
("Genymotion-like",      "virtualization", "",                     4),
("Anbox-like",           "virtualization", "",                     4),
("86Box",                "virtualization", "86Box/86Box",          3),
("PCem-like",            "virtualization", "",                     4),
("Vice C64",             "virtualization", "",                     3),
("Hatari",               "virtualization", "",                     4),
("Stella",               "virtualization", "stella-emu/stella",    3),
("Nestopia",             "virtualization", "",                     4),
("Kega-like",            "virtualization", "",                     4),
("Cemu",                 "virtualization", "cemu-project/Cemu",    2),
("Xemu",                 "virtualization", "xemu-project/xemu",    3),
("Rosalie Mupen GUI",    "virtualization", "Rosalie241/RMG",       4),
]


def seed_repos():
    """-> [(repo, name, category, tier)] for every seed with a known repo."""
    out, seen = [], set()
    for name, cat, repo, tier in SEEDS:
        if not repo or repo in seen:
            continue
        seen.add(repo)
        out.append((repo, name, cat, tier))
    return out


if __name__ == "__main__":
    import collections
    c = collections.Counter(s[1] for s in SEEDS)
    t = collections.Counter(s[3] for s in SEEDS)
    print("curated seed database: %d applications, %d with a known repo"
          % (len(SEEDS), len(seed_repos())))
    print("categories:", dict(c))
    print("tiers     :", dict(sorted(t.items())))
